-- Update exit_noc template to use placeholders instead of checkbox symbols
UPDATE document_templates SET content =
'<h1 style="text-align:center;">Employee Exit Clearance & No Objection Certificate (NOC)</h1>
<h2>1. Employee Information</h2>
<table style="width:100%;border-collapse:collapse;"><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Employee Name</strong></td><td style="border:1px solid #ccc;padding:6px;">{{employee_name}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Designation</strong></td><td style="border:1px solid #ccc;padding:6px;">{{designation}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Department</strong></td><td style="border:1px solid #ccc;padding:6px;">{{department}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Date of Joining</strong></td><td style="border:1px solid #ccc;padding:6px;">{{date_of_joining}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Last Working Date</strong></td><td style="border:1px solid #ccc;padding:6px;">{{last_working_date}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;"><strong>Separation Type</strong></td><td style="border:1px solid #ccc;padding:6px;">{{separation_type}}</td></tr></table>
<h2>2. Knowledge Transfer & Handover</h2>
<table style="width:100%;border-collapse:collapse;"><tr><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Particulars</th><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Status</th></tr><tr><td style="border:1px solid #ccc;padding:6px;">Project Handover Completed</td><td style="border:1px solid #ccc;padding:6px;">{{kt_project_handover}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Credentials/Documents Shared</td><td style="border:1px solid #ccc;padding:6px;">{{kt_credentials_shared}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Pending Tasks Updated</td><td style="border:1px solid #ccc;padding:6px;">{{kt_pending_tasks}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Client Communication Completed</td><td style="border:1px solid #ccc;padding:6px;">{{kt_client_communication}}</td></tr></table>
<h2>3. Company Asset Return</h2>
<table style="width:100%;border-collapse:collapse;"><tr><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Asset</th><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Return Status</th><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Condition</th></tr><tr><td style="border:1px solid #ccc;padding:6px;">Laptop / Desktop</td><td style="border:1px solid #ccc;padding:6px;">{{asset_laptop_status}}</td><td style="border:1px solid #ccc;padding:6px;">{{asset_laptop_condition}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Mobile Phone</td><td style="border:1px solid #ccc;padding:6px;">{{asset_phone_status}}</td><td style="border:1px solid #ccc;padding:6px;">{{asset_phone_condition}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">ID Card</td><td style="border:1px solid #ccc;padding:6px;">{{asset_idcard_status}}</td><td style="border:1px solid #ccc;padding:6px;">{{asset_idcard_condition}}</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Charger / Accessories</td><td style="border:1px solid #ccc;padding:6px;">{{asset_charger_status}}</td><td style="border:1px solid #ccc;padding:6px;">{{asset_charger_condition}}</td></tr></table>
<h2>4. Department Clearance</h2>
<table style="width:100%;border-collapse:collapse;"><tr><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Department</th><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Status</th><th style="border:1px solid #ccc;padding:6px;background:#f5f5f5;">Signature</th></tr><tr><td style="border:1px solid #ccc;padding:6px;">Reporting Manager</td><td style="border:1px solid #ccc;padding:6px;">{{clear_reporting_manager}}</td><td style="border:1px solid #ccc;padding:6px;">__________</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">HR Department</td><td style="border:1px solid #ccc;padding:6px;">{{clear_hr}}</td><td style="border:1px solid #ccc;padding:6px;">__________</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">Accounts & Finance</td><td style="border:1px solid #ccc;padding:6px;">{{clear_accounts}}</td><td style="border:1px solid #ccc;padding:6px;">__________</td></tr><tr><td style="border:1px solid #ccc;padding:6px;">IT / Admin</td><td style="border:1px solid #ccc;padding:6px;">{{clear_it}}</td><td style="border:1px solid #ccc;padding:6px;">__________</td></tr></table>
<hr/>
<p><strong>Employee Declaration</strong></p>
<p>I confirm that all company assets, documents, credentials, and responsibilities have been properly handed over.</p>
<p>Employee Signature: ____________________ &nbsp; Date: {{today}}</p>
<br/>
<p><strong>HR Final Clearance & NOC</strong></p>
<p>This is to certify that {{employee_name}} has completed all required exit formalities and departmental clearances. The organization has no objection to future employment opportunities.</p>
<p>Authorized HR Signature: ____________________ &nbsp; Date: ____________</p>'
WHERE template_key = 'exit_noc';
